//! Rust→TypeScript binding generation (the single source of truth for the
//! shape of every type that crosses the wire to the desktop app and mobile-web).
//!
//! Entirely gated behind the `ts-export` feature so a normal `cargo build` /
//! `cargo test` never pulls the `ts-rs` proc-macro. Regenerate + verify with:
//!
//! ```sh
//! cargo test -p claw-fleet-core --features ts-export --test ts_export
//! ```
//!
//! The generated bundle is emitted verbatim into BOTH consuming packages
//! (`claw-fleet-desktop/app/generated/types.ts` and
//! `mobile-web/src/generated/types.ts`). They are byte-identical generated
//! artifacts, not hand-maintained copies: one Rust source, one test run. The
//! drift-guard regenerates and `git diff --exit-code`s both, so a hand edit to
//! either — or a Rust struct change without regeneration — fails CI.
//!
//! To add a type: add `#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]`
//! to the Rust struct/enum, then list it in `emit!` below. The `emit!` list is
//! the authoritative registry of what is generated; anything not listed stays
//! hand-written in each app's `types.ts`.

#![cfg(feature = "ts-export")]

use ts_rs::{Config, TS};

/// Build the single self-contained bundle. `large_int = "number"` maps every
/// `u64`/`i64`/`u128`/`i128` to `number` globally (the wire value is a JS
/// number after `JSON.parse`; `bigint` would be a runtime type-lie), so no
/// per-field override is needed. All types live in one file, so `decl()`'s
/// reference-by-name output resolves without imports.
fn build_bundle() -> String {
    let cfg = Config::default().with_large_int("number");
    let mut out = String::new();
    out.push_str("// GENERATED by `cargo test -p claw-fleet-core --features ts-export`.\n");
    out.push_str("// DO NOT EDIT — edit the Rust structs in claw-fleet-core and regenerate.\n");
    out.push_str("// Source of truth: claw-fleet-core/tests/ts_export.rs\n\n");

    // ts-rs copies Rust doc comments verbatim into the TS output as `/** … */`
    // blocks. Rust prose is free to contain `*/` (e.g. a glob path like
    // `skills/*/SKILL.md`), which would close the JSDoc block early and desync
    // the TS parser — a silent build break gated only on unrelated Rust wording.
    // We don't need the implementation prose in a machine-generated wire-type
    // file, so strip every doc-comment line. ts-rs always emits comments on
    // their own lines (`/**`, ` * …`, ` */`) — never inline with a field — so a
    // stateless line filter is safe and also removes ~500 lines of noise.
    fn strip_doc_comments(decl: &str) -> String {
        decl.lines()
            .filter(|line| {
                let t = line.trim_start();
                !(t.starts_with("/**") || t.starts_with('*'))
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    macro_rules! emit {
        ($($t:ty),* $(,)?) => {
            $( out.push_str(&format!("export {}\n\n", strip_doc_comments(&<$t>::decl(&cfg)))); )*
        };
    }

    // ── cmd_ast: shell command structured view (GuardRequest.structuredCommand) ─
    emit!(
        claw_fleet_core::cmd_ast::CommandView,
        claw_fleet_core::cmd_ast::CommandLeaf,
        claw_fleet_core::cmd_ast::NestedScript,
        claw_fleet_core::cmd_ast::NestedKind,
        claw_fleet_core::cmd_ast::Connector,
    );

    // ── session ────────────────────────────────────────────────────────────
    emit!(
        claw_fleet_core::session::SessionStatus,
        claw_fleet_core::session::RateLimitState,
        claw_fleet_core::session::SessionInfo,
        claw_fleet_core::session_mark::SessionMark,
        claw_fleet_core::rate_limit_parser::RateLimitType,
        claw_fleet_core::today_usage::TodayUsage,
        claw_fleet_core::today_usage::ModelReceiptLine,
        claw_fleet_core::today_usage::TodayUsageBreakdown,
        claw_fleet_core::today_usage::DailyUsagePoint,
        claw_fleet_core::today_usage::UsageRangeBreakdown,
        claw_fleet_core::search_index::SearchHit,
        claw_fleet_core::backend::WaitingAlert,
        claw_fleet_core::backend::PendingDecisions,
        claw_fleet_core::skill_history::SkillInvocation,
    );

    // ── workflow ───────────────────────────────────────────────────────────
    emit!(
        claw_fleet_core::workflow::WorkflowAgentStatus,
        claw_fleet_core::workflow::WorkflowAgent,
        claw_fleet_core::workflow::WorkflowPhase,
        claw_fleet_core::workflow::WorkflowNodeKind,
        claw_fleet_core::workflow::WorkflowNodeStatus,
        claw_fleet_core::workflow::WorkflowNode,
        claw_fleet_core::workflow::WorkflowEdge,
        claw_fleet_core::workflow::WorkflowTree,
    );

    // ── token analysis ───────────────────────────────────────────────────────
    emit!(
        claw_fleet_core::token_analysis::UsageTotals,
        claw_fleet_core::token_analysis::SourceBuckets,
        claw_fleet_core::token_analysis::OutputBuckets,
        claw_fleet_core::token_analysis::SessionTokenBreakdown,
        claw_fleet_core::token_analysis::TaskTokenBreakdown,
        claw_fleet_core::codex_source::CodexTokenBreakdown,
        claw_fleet_core::dsh_source::DshTokenBreakdown,
        claw_fleet_core::dsh_cost::DshSessionCost,
    );

    // ── todos / bg / prd / handoff / live thinking ───────────────────────────
    emit!(
        claw_fleet_core::session_todos::TodoItem,
        claw_fleet_core::session_todos::TodoSummary,
        claw_fleet_core::bg_guard::BackgroundTask,
        claw_fleet_core::prd_tasks::TaskPlanSummary,
        claw_fleet_core::prd_tasks::TaskItem,
        claw_fleet_core::prd_tasks::TaskPlanDetail,
        claw_fleet_core::handoff::HandoffLink,
        claw_fleet_core::handoff::HandoffChain,
        claw_fleet_core::handoff::SessionHandoffInfo,
        claw_fleet_core::watch::WatchSummary,
        claw_fleet_core::live_thinking::LiveThinking,
    );

    // ── audit / guard ────────────────────────────────────────────────────────
    emit!(
        claw_fleet_core::audit::AuditRiskLevel,
        claw_fleet_core::audit::AuditEvent,
        claw_fleet_core::audit::AuditSummary,
        claw_fleet_core::audit::MatchMode,
        claw_fleet_core::audit::GuardAllowRule,
        claw_fleet_core::audit::AuditRuleInfo,
        claw_fleet_core::audit::SuggestedRule,
        claw_fleet_core::guard::GuardRequest,
    );

    // ── decision channels (elicitation / fleet-ask / plan / a2ui / perm) ──────
    emit!(
        claw_fleet_core::elicitation::ElicitationOption,
        claw_fleet_core::elicitation::ElicitationQuestion,
        claw_fleet_core::elicitation::ElicitationRequest,
        claw_fleet_core::mcp_ipc::FleetAskRequest,
        claw_fleet_core::mcp_ipc::FleetAskQuestion,
        claw_fleet_core::mcp_ipc::FleetAskImage,
        claw_fleet_core::mcp_ipc::FleetAskOption,
        claw_fleet_core::mcp_ipc::FleetAskFormField,
        claw_fleet_core::mcp_ipc::FormFieldKind,
        claw_fleet_core::mcp_ipc::ReviewDoc,
        claw_fleet_core::mcp_ipc::ReviewDocKind,
        claw_fleet_core::mcp_ipc::ReviewDocContent,
        claw_fleet_core::mcp_ipc::ReviewDocFormat,
        claw_fleet_core::plan_approval::PlanApprovalRequest,
        claw_fleet_core::mcp_a2ui_ipc::A2uiRenderRequest,
        claw_fleet_core::permission_prompt_ipc::PermissionPromptRequest,
    );

    // ── decision history ─────────────────────────────────────────────────────
    emit!(
        claw_fleet_core::decision_history::ElicitationOutcome,
        claw_fleet_core::decision_history::PlanApprovalOutcome,
        claw_fleet_core::decision_history::FleetAskOutcome,
        claw_fleet_core::decision_history::SelectedOption,
        claw_fleet_core::decision_history::DecisionHistoryRecord,
        claw_fleet_core::decision_history::UserPromptRecord,
        claw_fleet_core::decision_history::ElicitationRecord,
        claw_fleet_core::decision_history::FleetAskRecord,
        claw_fleet_core::decision_history::PlanApprovalRecord,
        claw_fleet_core::decision_history::DecisionTypeStats,
        claw_fleet_core::decision_history::DecisionCardStats,
    );

    // ── daily report / proc runner ───────────────────────────────────────────
    emit!(
        claw_fleet_core::daily_report::DailyReport,
        claw_fleet_core::daily_report::DailyMetrics,
        claw_fleet_core::daily_report::ModelTokens,
        claw_fleet_core::daily_report::ProjectMetrics,
        claw_fleet_core::daily_report::SessionSummary,
        claw_fleet_core::daily_report::DailyReportStats,
        claw_fleet_core::daily_report::Lesson,
        claw_fleet_core::lessons_store::ManagedLesson,
        claw_fleet_core::proc_runner::ProcStatus,
        claw_fleet_core::proc_runner::ProcRecord,
        claw_fleet_core::proc_runner::ProcOutputChunk,
    );

    out
}

#[test]
fn generate_ts_bindings() {
    let bundle = build_bundle();
    let manifest = env!("CARGO_MANIFEST_DIR");
    for rel in [
        "../claw-fleet-desktop/app/generated/types.ts",
        "../mobile-web/src/generated/types.ts",
    ] {
        let path = std::path::Path::new(manifest).join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &bundle).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    }
}
