//! Rust→TypeScript binding generation (the single source of truth for the
//! shape of every type that crosses the wire to the desktop app and mobile-web).
//!
//! Entirely gated behind the `ts-export` feature so a normal `cargo build` /
//! `cargo test` never pulls the `ts-rs` proc-macro. Regenerate + verify with:
//!
//! ```sh
//! cargo test -p claw-fleet-core --features ts-export --test ts_export
//! ```
//!
//! The generated bundle is emitted verbatim into BOTH consuming packages
//! (`claw-fleet-desktop/app/generated/types.ts` and
//! `mobile-web/src/generated/types.ts`). They are byte-identical generated
//! artifacts, not hand-maintained copies: one Rust source, one test run. The
//! drift-guard regenerates and `git diff --exit-code`s both, so a hand edit to
//! either — or a Rust struct change without regeneration — fails CI.
//!
//! To add a type: add `#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]`
//! to the Rust struct/enum, then list it in `emit!` below. The `emit!` list is
//! the authoritative registry of what is generated; anything not listed stays
//! hand-written in each app's `types.ts`.

#![cfg(feature = "ts-export")]

use ts_rs::{Config, TS};

/// Build the single self-contained bundle. `large_int = "number"` maps every
/// `u64`/`i64`/`u128`/`i128` to `number` globally (the wire value is a JS
/// number after `JSON.parse`; `bigint` would be a runtime type-lie), so no
/// per-field override is needed. All types live in one file, so `decl()`'s
/// reference-by-name output resolves without imports.
fn build_bundle() -> String {
    let cfg = Config::default().with_large_int("number");
    let mut out = String::new();
    out.push_str("// GENERATED by `cargo test -p claw-fleet-core --features ts-export`.\n");
    out.push_str("// DO NOT EDIT — edit the Rust structs in claw-fleet-core and regenerate.\n");
    out.push_str("// Source of truth: claw-fleet-core/tests/ts_export.rs\n\n");

    macro_rules! emit {
        ($($t:ty),* $(,)?) => {
            $( out.push_str(&format!("export {}\n\n", <$t>::decl(&cfg))); )*
        };
    }

    // ── cmd_ast: shell command structured view (GuardRequest.structuredCommand) ─
    emit!(
        claw_fleet_core::cmd_ast::CommandView,
        claw_fleet_core::cmd_ast::CommandLeaf,
        claw_fleet_core::cmd_ast::NestedScript,
        claw_fleet_core::cmd_ast::NestedKind,
        claw_fleet_core::cmd_ast::Connector,
    );

    out
}

#[test]
fn generate_ts_bindings() {
    let bundle = build_bundle();
    let manifest = env!("CARGO_MANIFEST_DIR");
    for rel in [
        "../claw-fleet-desktop/app/generated/types.ts",
        "../mobile-web/src/generated/types.ts",
    ] {
        let path = std::path::Path::new(manifest).join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &bundle).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    }
}
