import { describe, expect, it } from "vitest";
import { QR_FIXTURE_MATRIX, QR_FIXTURE_URL } from "./scanFrame.fixture";
import { readPairingFromFrame } from "./scanFrame";

/** Render module matrix into an RGBA frame, same shape as what `ctx.getImageData()` gives us:
 *  4 bytes per pixel, row-major, origin top-left. `scale` magnifies each module, `quiet` is
 *  the quiet zone around edges — QR spec requires 4-module quiet zone, most decoders skip without it. */
function renderFrame(matrix: readonly string[], scale: number, quiet: number) {
  const modules = matrix.length;
  const side = (modules + quiet * 2) * scale;
  const data = new Uint8ClampedArray(side * side * 4);
  for (let y = 0; y < side; y++) {
    for (let x = 0; x < side; x++) {
      const mx = Math.floor(x / scale) - quiet;
      const my = Math.floor(y / scale) - quiet;
      const dark =
        my >= 0 && my < modules && mx >= 0 && mx < modules && matrix[my][mx] === "#";
      const v = dark ? 0 : 255;
      const i = (y * side + x) * 4;
      data[i] = v;
      data[i + 1] = v;
      data[i + 2] = v;
      data[i + 3] = 255;
    }
  }
  return { data, width: side, height: side };
}

describe("readPairingFromFrame", () => {
  // This is the foundation of the whole scan entry: fixture is a real QR code generated by qrencode,
  // same RGBA frame type PairScanner feeds to the decoder. If this is green, the "camera → canvas →
  // jsQR → pairing link" pipeline is live.
  it("decodes pairing link from real QR code bitmap, including custom relay origin", () => {
    const { data, width, height } = renderFrame(QR_FIXTURE_MATRIX, 4, 4);
    const read = readPairingFromFrame(data, width, height);
    expect(read.sawCode).toBe(true);
    expect(read.paired).toEqual({
      secret: QR_FIXTURE_URL.split("#k=")[1],
      relayBase: "https://relay.selfhosted.example",
    });
  });

  it("decodes at different magnifications (not dependent on specific resolution)", () => {
    const { data, width, height } = renderFrame(QR_FIXTURE_MATRIX, 7, 4);
    expect(readPairingFromFrame(data, width, height).paired?.relayBase).toBe(
      "https://relay.selfhosted.example",
    );
  });

  // Tested: quiet zone of 0 — QR code fills the frame — jsQR still decodes it. I originally
  // assumed it would fail (spec requires 4-module quiet zone), but testing proved otherwise.
  // Reason to pin this: viewport can be drawn tight, user filling the frame won't prevent scan,
  // no need for "step back" hints.
  it("decodes with quiet zone of 0 (tested, contrary to spec requirement)", () => {
    const { data, width, height } = renderFrame(QR_FIXTURE_MATRIX, 4, 0);
    expect(readPairingFromFrame(data, width, height).paired?.relayBase).toBe(
      "https://relay.selfhosted.example",
    );
  });

  it("blank white frame: neither sees code nor returns pairing link", () => {
    const side = 64;
    const data = new Uint8ClampedArray(side * side * 4).fill(255);
    expect(readPairingFromFrame(data, side, side)).toEqual({ paired: null, sawCode: false });
  });
});
