-- Fleet Cloud uses UUIDs generated by the application and keeps the database
-- extension-free so the same migration runs in local Docker and Muvee.
CREATE TABLE IF NOT EXISTS fleet_schema_migrations_guard (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
