//! Reverse-engineered parser for Claude Code rate-limit error messages.
//!
//! Claude Code persists rate-limit errors to its JSONL transcript with the
//! reset time rendered as a human-readable string (e.g. `"10:30pm
//! (America/Los_Angeles)"`), not a Unix timestamp. This module recovers the
//! exact reset `DateTime<Utc>` from that string.
//!
//! Format sourced from `claude-code-fork/src/utils/format.ts::formatResetTime`
//! and `src/services/rateLimitMessages.ts::formatLimitReachedText`. See
//! `testdata/reset_time_golden.jsonl` for golden outputs generated by running
//! the real `formatResetTime` under multiple IANA time zones.

use chrono::{DateTime, Datelike, Duration, NaiveDate, TimeZone, Utc};
use chrono_tz::Tz;

/// Which rate-limit bucket the user hit, parsed from the error prefix.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RateLimitType {
    /// "You've hit your session limit" — 5-hour rolling window
    SessionLimit,
    /// "You've hit your weekly limit" — 7-day (also used for Sonnet-weekly on pro/enterprise)
    WeeklyLimit,
    /// "You've hit your Opus limit"
    OpusLimit,
    /// "You've hit your Sonnet limit" (non-pro/enterprise)
    SonnetLimit,
    /// "You've hit your usage limit" — generic, no rateLimitType header
    UsageLimit,
    /// "You're out of extra usage" — overage exhausted
    OutOfExtraUsage,
    /// Could not classify
    Unknown,
}

impl RateLimitType {
    /// Fallback duration to add to the error timestamp when the reset string is unparseable.
    pub fn fallback_duration(&self) -> Duration {
        match self {
            RateLimitType::SessionLimit => Duration::hours(5),
            RateLimitType::WeeklyLimit
            | RateLimitType::OpusLimit
            | RateLimitType::SonnetLimit
            | RateLimitType::OutOfExtraUsage => Duration::days(7),
            // Conservative default: 5h, so UI doesn't pretend we know better.
            RateLimitType::UsageLimit | RateLimitType::Unknown => Duration::hours(5),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum EstimateReason {
    /// No `· resets <X>` segment found in the content.
    NoResetsSegment,
    /// Segment found but parse failed.
    ParseFailed(String),
    /// Time zone name in parentheses was not a recognized IANA zone.
    UnknownTimeZone(String),
    /// Wall-clock time was invalid or ambiguous in the given zone (DST hole).
    InvalidWallClock,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ParsedRateLimit {
    pub resets_at: DateTime<Utc>,
    pub limit_type: RateLimitType,
    /// True when `resets_at` was derived from the rendered string;
    /// false when it's a fallback estimate computed from the error timestamp.
    pub parsed: bool,
    /// Only set when `parsed == false`.
    pub estimate_reason: Option<EstimateReason>,
}

/// Parse a Claude Code rate-limit assistant-message `content.text` into a
/// precise `resets_at` timestamp. If the rendered string cannot be recovered,
/// returns an estimate based on `error_timestamp + limit_type.fallback_duration()`.
pub fn parse_rate_limit_content(
    content: &str,
    error_timestamp: DateTime<Utc>,
) -> ParsedRateLimit {
    let limit_type = classify_limit_type(content);

    let Some(reset_segment) = extract_reset_segment(content) else {
        return estimate(limit_type, error_timestamp, EstimateReason::NoResetsSegment);
    };

    match parse_reset_segment(reset_segment, error_timestamp) {
        Ok(resets_at) => ParsedRateLimit {
            resets_at,
            limit_type,
            parsed: true,
            estimate_reason: None,
        },
        Err(reason) => estimate(limit_type, error_timestamp, reason),
    }
}

fn estimate(
    limit_type: RateLimitType,
    error_timestamp: DateTime<Utc>,
    reason: EstimateReason,
) -> ParsedRateLimit {
    ParsedRateLimit {
        resets_at: error_timestamp + limit_type.fallback_duration(),
        limit_type,
        parsed: false,
        estimate_reason: Some(reason),
    }
}

fn classify_limit_type(content: &str) -> RateLimitType {
    // Prefix order matters: "session" / "weekly" / "Opus" / "Sonnet" / "usage"
    // are disjoint under "You've hit your <X> limit".
    if content.starts_with("You're out of extra usage") {
        return RateLimitType::OutOfExtraUsage;
    }
    if !content.starts_with("You've hit your ") {
        return RateLimitType::Unknown;
    }
    let tail = &content["You've hit your ".len()..];
    if tail.starts_with("session limit") {
        RateLimitType::SessionLimit
    } else if tail.starts_with("weekly limit") {
        RateLimitType::WeeklyLimit
    } else if tail.starts_with("Opus limit") {
        RateLimitType::OpusLimit
    } else if tail.starts_with("Sonnet limit") {
        RateLimitType::SonnetLimit
    } else if tail.starts_with("usage limit") {
        RateLimitType::UsageLimit
    } else if tail.starts_with("limit") {
        // Historical/legacy format (observed in production JSONL from 2026-03):
        //   "You've hit your limit · resets 7pm (Asia/Shanghai)"
        // Current claude-code source never emits this bare form, but older
        // versions did. Treat as Unknown-type but still parse reset time.
        RateLimitType::Unknown
    } else {
        RateLimitType::Unknown
    }
}

/// Extract the substring following `· resets ` up to (exclusive) the next ` · `
/// or end of string. Uses the middle-dot character `·` (U+00B7), which is what
/// `formatLimitReachedText` emits.
fn extract_reset_segment(content: &str) -> Option<&str> {
    let marker = "· resets ";
    let start = content.find(marker)? + marker.len();
    let tail = &content[start..];
    // Stop at the next " · " separator (Ant users have " · /reset-limits" trailer).
    // Also stop at '.' so "If you have feedback..." sentence tail is excluded.
    let end = tail
        .find(" · ")
        .or_else(|| tail.find(". "))
        .unwrap_or(tail.len());
    Some(tail[..end].trim_end())
}

/// Parse `"Apr 17, 9:30pm (America/Los_Angeles)"` or `"10:30pm (America/Los_Angeles)"`
/// into a UTC instant.
fn parse_reset_segment(
    segment: &str,
    error_timestamp: DateTime<Utc>,
) -> Result<DateTime<Utc>, EstimateReason> {
    // 1. Split off " (<tz>)" from the end.
    let (time_part, tz_name) = split_trailing_tz(segment)
        .ok_or_else(|| EstimateReason::ParseFailed(format!("no trailing tz in {segment:?}")))?;

    let tz: Tz = tz_name
        .parse()
        .map_err(|_| EstimateReason::UnknownTimeZone(tz_name.to_string()))?;

    // 2. Discriminate branch A vs B by presence of a three-letter month prefix.
    if starts_with_month_abbrev(time_part) {
        parse_branch_a(time_part, tz, error_timestamp)
    } else {
        parse_branch_b(time_part, tz, error_timestamp)
    }
}

/// Split `"<rest> (<tz>)"` → `("<rest>", "<tz>")`. The tz spans from the last
/// ` (` to a trailing `)`. Everything before that is `rest`.
fn split_trailing_tz(segment: &str) -> Option<(&str, &str)> {
    let segment = segment.trim_end();
    if !segment.ends_with(')') {
        return None;
    }
    let without_paren = &segment[..segment.len() - 1];
    let open_idx = without_paren.rfind(" (")?;
    let rest = &without_paren[..open_idx];
    let tz = &without_paren[open_idx + 2..];
    Some((rest.trim_end(), tz))
}

const MONTH_ABBREVS: [(&str, u32); 12] = [
    ("Jan", 1),
    ("Feb", 2),
    ("Mar", 3),
    ("Apr", 4),
    ("May", 5),
    ("Jun", 6),
    ("Jul", 7),
    ("Aug", 8),
    ("Sep", 9),
    ("Oct", 10),
    ("Nov", 11),
    ("Dec", 12),
];

fn starts_with_month_abbrev(s: &str) -> bool {
    MONTH_ABBREVS
        .iter()
        .any(|(abbrev, _)| s.starts_with(abbrev) && s.as_bytes().get(3) == Some(&b' '))
}

/// Branch A: `"<Mon> <D>[, <YYYY>], <time>"`
fn parse_branch_a(
    input: &str,
    tz: Tz,
    error_timestamp: DateTime<Utc>,
) -> Result<DateTime<Utc>, EstimateReason> {
    // Month
    let (month_abbrev, rest) = input.split_once(' ').ok_or_else(|| {
        EstimateReason::ParseFailed(format!("branch A: no space after month in {input:?}"))
    })?;
    let month = MONTH_ABBREVS
        .iter()
        .find(|(a, _)| *a == month_abbrev)
        .map(|(_, m)| *m)
        .ok_or_else(|| {
            EstimateReason::ParseFailed(format!("branch A: unknown month {month_abbrev:?}"))
        })?;

    // After month: "<D>[, <YYYY>], <time>" or "<D>, <time>"
    // Split on ", " — could be 1 or 2 splits.
    let parts: Vec<&str> = rest.splitn(3, ", ").collect();
    let (day_str, year_opt, time_str) = match parts.as_slice() {
        // "<D>, <time>"
        [day, time] => (*day, None, *time),
        // "<D>, <YYYY>, <time>"
        [day, year, time] => (*day, Some(*year), *time),
        _ => {
            return Err(EstimateReason::ParseFailed(format!(
                "branch A: unexpected shape {rest:?}"
            )))
        }
    };

    let day: u32 = day_str
        .parse()
        .map_err(|_| EstimateReason::ParseFailed(format!("branch A: bad day {day_str:?}")))?;

    let (hour24, minute) = parse_hour_minute_ampm(time_str)?;

    // Determine year
    let error_in_tz = error_timestamp.with_timezone(&tz);
    let base_year = error_in_tz.year();
    let year: i32 = if let Some(y) = year_opt {
        y.parse()
            .map_err(|_| EstimateReason::ParseFailed(format!("branch A: bad year {y:?}")))?
    } else {
        // No year in string → same year as error, unless that places the
        // reset in the past (e.g. error 2026-12-31, reset "Jan 2 …" → 2027).
        let candidate = NaiveDate::from_ymd_opt(base_year, month, day).ok_or_else(|| {
            EstimateReason::ParseFailed(format!("branch A: invalid date {base_year}-{month}-{day}"))
        })?;
        let candidate_dt = candidate
            .and_hms_opt(hour24, minute, 0)
            .ok_or(EstimateReason::InvalidWallClock)?;
        let candidate_utc = localize(tz, candidate_dt)?;
        if candidate_utc < error_timestamp {
            base_year + 1
        } else {
            base_year
        }
    };

    let date = NaiveDate::from_ymd_opt(year, month, day).ok_or_else(|| {
        EstimateReason::ParseFailed(format!("branch A: invalid date {year}-{month}-{day}"))
    })?;
    let naive_dt = date
        .and_hms_opt(hour24, minute, 0)
        .ok_or(EstimateReason::InvalidWallClock)?;
    localize(tz, naive_dt)
}

/// Branch B: `"<time>"` — base date is the error timestamp in `tz`; if the
/// resulting wall-clock is at or before the error timestamp, roll forward one day.
fn parse_branch_b(
    input: &str,
    tz: Tz,
    error_timestamp: DateTime<Utc>,
) -> Result<DateTime<Utc>, EstimateReason> {
    let (hour24, minute) = parse_hour_minute_ampm(input)?;

    let error_in_tz = error_timestamp.with_timezone(&tz);
    let base_date = error_in_tz.date_naive();

    let naive_today = base_date
        .and_hms_opt(hour24, minute, 0)
        .ok_or(EstimateReason::InvalidWallClock)?;
    let today_utc = localize(tz, naive_today)?;

    if today_utc > error_timestamp {
        Ok(today_utc)
    } else {
        let naive_tomorrow = (base_date + Duration::days(1))
            .and_hms_opt(hour24, minute, 0)
            .ok_or(EstimateReason::InvalidWallClock)?;
        localize(tz, naive_tomorrow)
    }
}

/// Parse `"9:30pm"`, `"9pm"`, `"12am"`, `"12pm"` into `(hour24, minute)`.
fn parse_hour_minute_ampm(s: &str) -> Result<(u32, u32), EstimateReason> {
    let s = s.trim();
    let (num_part, ampm) = if let Some(body) = s.strip_suffix("am") {
        (body, false)
    } else if let Some(body) = s.strip_suffix("pm") {
        (body, true)
    } else {
        return Err(EstimateReason::ParseFailed(format!(
            "time: no am/pm suffix in {s:?}"
        )));
    };

    let (hour12, minute) = if let Some((h, m)) = num_part.split_once(':') {
        let h: u32 = h
            .parse()
            .map_err(|_| EstimateReason::ParseFailed(format!("time: bad hour {h:?}")))?;
        let m: u32 = m
            .parse()
            .map_err(|_| EstimateReason::ParseFailed(format!("time: bad minute {m:?}")))?;
        (h, m)
    } else {
        let h: u32 = num_part
            .parse()
            .map_err(|_| EstimateReason::ParseFailed(format!("time: bad hour {num_part:?}")))?;
        (h, 0)
    };

    if hour12 == 0 || hour12 > 12 || minute >= 60 {
        return Err(EstimateReason::ParseFailed(format!(
            "time: out of range {hour12}:{minute:02}"
        )));
    }

    // 12am → 0, 12pm → 12, 1-11am → 1-11, 1-11pm → 13-23.
    let hour24 = match (hour12, ampm) {
        (12, false) => 0,
        (12, true) => 12,
        (h, false) => h,
        (h, true) => h + 12,
    };
    Ok((hour24, 0.max(minute)))
}

/// Attach a naive wall-clock to an IANA zone, resolving ambiguities
/// conservatively: pick the earlier instant for ambiguous (fall-back DST),
/// and fail for non-existent (spring-forward) — falling back to estimation.
fn localize(
    tz: Tz,
    naive: chrono::NaiveDateTime,
) -> Result<DateTime<Utc>, EstimateReason> {
    use chrono::offset::LocalResult;
    match tz.from_local_datetime(&naive) {
        LocalResult::Single(dt) => Ok(dt.with_timezone(&Utc)),
        LocalResult::Ambiguous(earlier, _) => Ok(earlier.with_timezone(&Utc)),
        LocalResult::None => Err(EstimateReason::InvalidWallClock),
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;
    use std::fs;
    use std::path::PathBuf;

    #[derive(Debug, serde::Deserialize)]
    struct GoldenRow {
        label: String,
        tz: String,
        now_unix: i64,
        resets_at_unix: i64,
        output: String,
    }

    fn load_golden() -> Vec<GoldenRow> {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata")
            .join("reset_time_golden.jsonl");
        let text = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read golden {path:?}: {e}"));
        text.lines()
            .filter(|l| !l.trim().is_empty())
            .map(|l| serde_json::from_str(l).expect("parse golden row"))
            .collect()
    }

    /// Wrap a bare `formatResetTime` output inside a realistic
    /// `formatLimitReachedText` envelope so the parser exercises the full
    /// `classify_limit_type` + `extract_reset_segment` path.
    fn wrap(output: &str, limit: &str) -> String {
        format!("You've hit your {limit} · resets {output}")
    }

    /// All golden rows must round-trip: parsing the rendered string recovers
    /// the exact Unix timestamp that was fed to formatResetTime.
    #[test]
    fn golden_roundtrip_all_rows() {
        let rows = load_golden();
        assert!(rows.len() >= 80, "expected ≥80 golden rows, got {}", rows.len());

        let mut failures = Vec::new();
        for row in &rows {
            let content = wrap(&row.output, "session limit");
            let error_ts = Utc.timestamp_opt(row.now_unix, 0).unwrap();
            let result = parse_rate_limit_content(&content, error_ts);
            if !result.parsed {
                failures.push(format!(
                    "[{}/{}] not parsed: reason={:?}, output={:?}",
                    row.label, row.tz, result.estimate_reason, row.output
                ));
                continue;
            }
            let expected = Utc.timestamp_opt(row.resets_at_unix, 0).unwrap();
            if result.resets_at != expected {
                failures.push(format!(
                    "[{}/{}] mismatch: got {}, expected {}, output={:?}",
                    row.label, row.tz, result.resets_at, expected, row.output
                ));
            }
        }
        if !failures.is_empty() {
            panic!(
                "{} of {} golden rows failed:\n{}",
                failures.len(),
                rows.len(),
                failures.join("\n")
            );
        }
    }

    #[test]
    fn classify_session_limit() {
        assert_eq!(
            classify_limit_type("You've hit your session limit · resets 10pm (UTC)"),
            RateLimitType::SessionLimit
        );
    }

    #[test]
    fn classify_weekly_limit() {
        assert_eq!(
            classify_limit_type("You've hit your weekly limit · resets Apr 17, 9pm (UTC)"),
            RateLimitType::WeeklyLimit
        );
    }

    #[test]
    fn classify_opus_limit() {
        assert_eq!(
            classify_limit_type("You've hit your Opus limit · resets 10pm (UTC)"),
            RateLimitType::OpusLimit
        );
    }

    #[test]
    fn classify_sonnet_limit() {
        assert_eq!(
            classify_limit_type("You've hit your Sonnet limit · resets 10pm (UTC)"),
            RateLimitType::SonnetLimit
        );
    }

    #[test]
    fn classify_usage_limit() {
        assert_eq!(
            classify_limit_type("You've hit your usage limit · resets 10pm (UTC)"),
            RateLimitType::UsageLimit
        );
    }

    #[test]
    fn classify_out_of_extra_usage() {
        assert_eq!(
            classify_limit_type("You're out of extra usage · resets Apr 17, 9pm (UTC)"),
            RateLimitType::OutOfExtraUsage
        );
    }

    #[test]
    fn classify_unknown_prefix() {
        assert_eq!(classify_limit_type("Some other error"), RateLimitType::Unknown);
    }

    #[test]
    fn fallback_durations() {
        assert_eq!(RateLimitType::SessionLimit.fallback_duration(), Duration::hours(5));
        assert_eq!(RateLimitType::WeeklyLimit.fallback_duration(), Duration::days(7));
        assert_eq!(RateLimitType::OpusLimit.fallback_duration(), Duration::days(7));
        assert_eq!(RateLimitType::UsageLimit.fallback_duration(), Duration::hours(5));
    }

    #[test]
    fn parse_hour_minute_variants() {
        assert_eq!(parse_hour_minute_ampm("10pm").unwrap(), (22, 0));
        assert_eq!(parse_hour_minute_ampm("10:30pm").unwrap(), (22, 30));
        assert_eq!(parse_hour_minute_ampm("12am").unwrap(), (0, 0));
        assert_eq!(parse_hour_minute_ampm("12pm").unwrap(), (12, 0));
        assert_eq!(parse_hour_minute_ampm("1am").unwrap(), (1, 0));
        assert_eq!(parse_hour_minute_ampm("11:59pm").unwrap(), (23, 59));
    }

    #[test]
    fn parse_hour_minute_rejects_bad() {
        assert!(parse_hour_minute_ampm("13pm").is_err());
        assert!(parse_hour_minute_ampm("0am").is_err());
        assert!(parse_hour_minute_ampm("10:60pm").is_err());
        assert!(parse_hour_minute_ampm("10").is_err());
    }

    #[test]
    fn extract_segment_stops_at_ant_trailer() {
        let content = "You've hit your session limit · resets 10pm (UTC) · If you have feedback about this limit, post in #briarpatch-cc. You can reset your limits with /reset-limits";
        let seg = extract_reset_segment(content).unwrap();
        assert_eq!(seg, "10pm (UTC)");
    }

    #[test]
    fn extract_segment_no_marker_returns_none() {
        assert!(extract_reset_segment("Some other error").is_none());
    }

    #[test]
    fn no_resets_segment_falls_back_to_estimate() {
        let error_ts = Utc.with_ymd_and_hms(2026, 4, 15, 10, 0, 0).unwrap();
        let result = parse_rate_limit_content("You've hit your session limit", error_ts);
        assert!(!result.parsed);
        assert_eq!(result.estimate_reason, Some(EstimateReason::NoResetsSegment));
        assert_eq!(result.resets_at, error_ts + Duration::hours(5));
    }

    #[test]
    fn unknown_tz_falls_back_to_estimate() {
        let error_ts = Utc.with_ymd_and_hms(2026, 4, 15, 10, 0, 0).unwrap();
        let content = "You've hit your session limit · resets 10pm (NotAZone/Fake)";
        let result = parse_rate_limit_content(content, error_ts);
        assert!(!result.parsed);
        match result.estimate_reason {
            Some(EstimateReason::UnknownTimeZone(tz)) => assert_eq!(tz, "NotAZone/Fake"),
            other => panic!("unexpected reason: {other:?}"),
        }
    }

    #[test]
    fn ant_trailer_still_parses_cleanly() {
        let error_ts = Utc.with_ymd_and_hms(2026, 4, 15, 10, 0, 0).unwrap();
        let content = "You've hit your session limit · resets 6pm (UTC) · If you have feedback about this limit, post in #briarpatch-cc. You can reset your limits with /reset-limits";
        let result = parse_rate_limit_content(content, error_ts);
        assert!(result.parsed, "should parse despite Ant trailer");
        assert_eq!(
            result.resets_at,
            Utc.with_ymd_and_hms(2026, 4, 15, 18, 0, 0).unwrap()
        );
        assert_eq!(result.limit_type, RateLimitType::SessionLimit);
    }

    #[test]
    fn branch_b_rolls_to_tomorrow_when_time_in_past() {
        // Error at 22:00 UTC, reset "10pm" in UTC = today 22:00 = exactly the error.
        // Parser should roll to tomorrow 22:00.
        let error_ts = Utc.with_ymd_and_hms(2026, 4, 15, 22, 0, 0).unwrap();
        let content = "You've hit your session limit · resets 10pm (UTC)";
        let result = parse_rate_limit_content(content, error_ts);
        assert!(result.parsed);
        assert_eq!(
            result.resets_at,
            Utc.with_ymd_and_hms(2026, 4, 16, 22, 0, 0).unwrap()
        );
    }

    /// Real content strings harvested from the user's own ~/.claude/projects/
    /// JSONL files across multiple projects and dates. These are verbatim
    /// reproductions of what actually hit the disk during rate-limit events.
    ///
    /// Each row: (iso_timestamp, content, expected_parsed, expected_limit_type).
    /// For parsed rows, the timestamp + content must produce a `resets_at`
    /// in the future relative to the error timestamp.
    #[test]
    fn real_world_jsonl_samples() {
        struct Sample {
            error_iso: &'static str,
            content: &'static str,
            should_parse: bool,
            limit_type: RateLimitType,
        }

        let samples = [
            // ── From -Users-hoveychen-workspace-ashare-prod (2026-03-17) ────
            // Legacy "You've hit your limit" form (no explicit limit type).
            Sample {
                error_iso: "2026-03-17T08:08:23.718Z",
                content: "You've hit your limit · resets 7pm (Asia/Shanghai)",
                should_parse: true,
                limit_type: RateLimitType::Unknown,
            },
            Sample {
                error_iso: "2026-03-17T08:10:04.234Z",
                content: "You've hit your limit · resets 7pm (Asia/Shanghai)",
                should_parse: true,
                limit_type: RateLimitType::Unknown,
            },
            // ── From -Users-hoveychen-workspace-netferry (2026-03-28) ───────
            Sample {
                error_iso: "2026-03-28T13:06:39.214Z",
                content: "You've hit your limit · resets 10pm (Asia/Shanghai)",
                should_parse: true,
                limit_type: RateLimitType::Unknown,
            },
            // ── From -Users-hoveychen-workspace-bobo-gambler (2026-04-05) ───
            // Capacity-type 429 with NO reset info — must gracefully estimate.
            Sample {
                error_iso: "2026-04-05T15:32:54.581Z",
                content: "API Error: Request rejected (429) · Rate limited",
                should_parse: false,
                limit_type: RateLimitType::Unknown,
            },
        ];

        for s in &samples {
            let error_ts: DateTime<Utc> = s.error_iso.parse().unwrap();
            let result = parse_rate_limit_content(s.content, error_ts);
            assert_eq!(
                result.parsed, s.should_parse,
                "parsed mismatch for {:?}: got {:?}, reason={:?}",
                s.content, result.parsed, result.estimate_reason
            );
            assert_eq!(
                result.limit_type, s.limit_type,
                "limit_type mismatch for {:?}",
                s.content
            );
            // All samples must produce a future resets_at (even estimates).
            assert!(
                result.resets_at > error_ts,
                "resets_at {} not after error {} for {:?}",
                result.resets_at,
                error_ts,
                s.content
            );
        }

        // Spot-check the Shanghai 7pm case: 08:08 UTC on 2026-03-17 = 16:08
        // Asia/Shanghai, so "7pm" = today 19:00 CST = 11:00 UTC same day.
        let r = parse_rate_limit_content(
            "You've hit your limit · resets 7pm (Asia/Shanghai)",
            "2026-03-17T08:08:23.718Z".parse().unwrap(),
        );
        assert!(r.parsed);
        assert_eq!(
            r.resets_at,
            Utc.with_ymd_and_hms(2026, 3, 17, 11, 0, 0).unwrap()
        );

        // Spot-check the "Request rejected" fallback: Unknown limit type
        // uses 5-hour fallback duration.
        let r = parse_rate_limit_content(
            "API Error: Request rejected (429) · Rate limited",
            "2026-04-05T15:32:54.581Z".parse().unwrap(),
        );
        assert!(!r.parsed);
        assert_eq!(
            r.estimate_reason,
            Some(EstimateReason::NoResetsSegment)
        );
        let expected_ts: DateTime<Utc> = "2026-04-05T15:32:54.581Z".parse().unwrap();
        assert_eq!(r.resets_at, expected_ts + Duration::hours(5));
    }

    #[test]
    fn branch_a_no_year_picks_next_year_across_boundary() {
        // Error on Dec 31, reset "Jan 2, 11am (UTC)" — no year → should pick next year.
        let error_ts = Utc.with_ymd_and_hms(2026, 12, 31, 12, 0, 0).unwrap();
        let content = "You've hit your weekly limit · resets Jan 2, 11am (UTC)";
        let result = parse_rate_limit_content(content, error_ts);
        assert!(result.parsed);
        assert_eq!(
            result.resets_at,
            Utc.with_ymd_and_hms(2027, 1, 2, 11, 0, 0).unwrap()
        );
    }
}
